#!/bin/sh
#
# Test that SPF self-validation populates the RFC 6591 SPF-DNS field
# (RFC 9991) of a captured failure report, via LogSPFDNS.

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

miltertest -s $srcdir/t-verify-self-spf-report.lua
