#!/bin/sh
#
# Test a fake message using our internal SPF implementation.  Confirm
# the right Authentication-Results is generated.

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

miltertest -s $srcdir/t-verify-self-spf.lua
