#!/bin/sh
#
# Test a multi-valued From field that's malformed to ensure we don't crash.
#

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

miltertest -s $srcdir/t-verify-multi-from-malformed.lua -v -v -v
